5|D
  4|(GAB||5|C)D
  4|GG

5|E
  5|(((CD||4|B||5|C))DEF#)G
  4|GG
  
5|((CD||4|B||5|C))(DC||4|BA)
  B(||5|C||4|BAG)
  F#(GABG)
  (BA)[A]
  
5|D
  4|(GAB||5|C)D
  4|GG

5|E
  5|(((CD||4|B||5|C))DEF#)G
  4|GG
  
5|((CD||4|B||5|C))(DC||4|BA)
  B(||5|C||4|BAG)
  A(BAGF#)
  [G]G
  
&&&

3|[G]A
3|[B]B
4|[C]C
3|[B]B
3|[A]A
3|[G]G

4|D||3|BG
4|D
  3|(D||4|C||3|BA)
  
3|[B]A
3|GBG
4|[C]C
3|B
  4|(C||3|BAG)
3|[A]F#
3|[G]B
4|CD||3|D
3|[G]||2|[G]
